language: python
python:
- "2.6"
- "2.7"
- "3.5"

install: 
- "pip install -r requirements.txt"

script: 
- "wget https://github.com/SpectoLabs/myna/releases/download/v1/myna"
- "export PATH=$PWD:$PATH"
- "make test"
